### PR TITLE
Revert "Some 0.4 fixes"

### PR DESCRIPTION
**Pull request by pao**
Reverts pao/StrPack.jl#19

### CODE REVIEW

**Comment by pao** [comment]
@keno, on second thought, bad idea. Needs an update in REQUIREMENTS too.

**Comment by Keno** [comment]
You mean for Compat?

**Comment by pao** [comment]
yes, will fix if I can figure out how to drive this crazy thing

**Comment by Keno** [comment]
what are you driving? I noticed an impressively fast revert there.

**Comment by pao** [comment]
GitHub. Fast revert was because I realized my mistake about that fast.

**Comment by pao** [comment]
ugh, never mind, I hate this now, I'll just one-off clone this to do it

**Comment by pao** [comment]
alright, done, sorry for the extraneous noise

**Pull request merged**
